### ISSUE TITLE
instrument basic event tracking

### ISSUE THREAD

**Issue by drewbanin** [analyst-collective/dbt#89]

**Comment by drewbanin** [comment]
- [] Ping fivetran about snowplow python events

- [ ] unstructured events
- [ ] opt-out config (goes in `profile.yml`)
- [ ] ip
- [ ] user uuid 
- [ ] version
- [ ] hashed node names - start (1 per model run)
- [ ] hashed node names - end (1 per model run)
- [ ] top-level error message (if errored) sans stack trace

"job" events
"node" events

- [ ] should also work for dbt test
- [ ] should be able to discern between "dry" runs and "real" runs (in job)
- [ ] uuid for job, models use this id
- [ ] debug, init, compile, run... these are all jobs/instantiations/invocation/etc
